import type { Metadata } from 'next'
import React from 'react'
import { Onest } from 'next/font/google'
import './globals.css'

const onest = Onest({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <title>Todo App</title>
      </head>
      <body className={onest.className}>
        <h1 className='mt-5 text-2xl font-semibold text-center'>Todo App</h1>
        {children}
      </body>
    </html>
  )
}
